apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  sa-password: "Karim@Salah2025"
  connection-string: "Server=sqlserver;Database=weatherDB;User Id=sa;Password=Karim@Salah2025;TrustServerCertificate=True"