apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-backend
  labels:
    app: weatherapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp-backend
  template:
    metadata:
      labels:
        app: weatherapp-backend
    spec:
      containers:
      - name: backend
        image: YOUR_DOCKERHUB_USERNAME/weatherapp-backend:latest  # Will be updated by pipeline
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: connection-string
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-backend
  labels:
    app: weatherapp-backend
spec:
  selector:
    app: weatherapp-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP