apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-backend
  labels:
    app: weatherapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-backend
  template:
    metadata:
      labels:
        app: weatherapp-backend
    spec:
      containers:
      - name: weatherapp-backend
        image: engkarimsalah/weatherapp-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: connection-string
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-backend
  labels:
    app: weatherapp-backend
spec:
  selector:
    app: weatherapp-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
