apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-frontend
  labels:
    app: weatherapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-frontend
  template:
    metadata:
      labels:
        app: weatherapp-frontend
    spec:
      containers:
      - name: weatherapp-frontend
        image: engkarimsalah/weatherapp-frontend:latest  # Will be updated by pipeline
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-frontend
  labels:
    app: weatherapp-frontend
spec:
  selector:
    app: weatherapp-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30085
  type: NodePort
